// Real Ta3laM Power BI curriculum — 7 stages, 50 lessons
window.CURRICULUM = [
  {
    id: "foundations",
    num: "01",
    title: "أساسيات نمذجة البيانات",
    en: "Data Modeling Foundations",
    subtitle: "Data Modeling Foundations",
    accent: "gold",
    lessons: [
      { id: "intro",         title: "مقدمة في Power BI",                en: "Intro to Power BI",             mins: 8,  kind: "concept" },
      { id: "setup",         title: "التثبيت والإعداد",                 en: "Installation & Setup",          mins: 6,  kind: "practice" },
      { id: "interface",     title: "واجهة البرنامج",                   en: "Interface Overview",            mins: 9,  kind: "concept" },
      { id: "oltp-olap",     title: "OLTP مقابل OLAP",                  en: "OLTP vs OLAP",                  mins: 11, kind: "theory" },
      { id: "model",         title: "نموذج البيانات والـ Star Schema",  en: "Data Model & Star Schema",      mins: 14, kind: "theory" },
      { id: "scd",           title: "الأبعاد المتغيرة ببطء",            en: "Slowly Changing Dimensions",    mins: 12, kind: "theory" },
      { id: "bridge-tables", title: "الجداول الجسرية",                  en: "Bridge Tables",                 mins: 10, kind: "theory" },
    ],
  },
  {
    id: "data",
    num: "02",
    title: "هندسة البيانات وتحويلها",
    en: "Data Engineering & Transformation",
    subtitle: "Power Query · M Language",
    accent: "teal",
    lessons: [
      { id: "getdata",     title: "جلب البيانات",            en: "Get Data",         mins: 7,  kind: "practice" },
      { id: "cleaning",    title: "تنظيف البيانات",           en: "Data Cleaning",    mins: 12, kind: "practice" },
      { id: "powerquery",  title: "محرر Power Query",          en: "Power Query",      mins: 18, kind: "practice" },
      { id: "mcode",       title: "لغة M المتقدمة",            en: "Advanced M Code",  mins: 22, kind: "code" },
    ],
  },
  {
    id: "modeling",
    num: "03",
    title: "بناء النموذج الربطي",
    en: "Building the Data Model",
    subtitle: "Data Modeling in Power BI",
    accent: "blue",
    lessons: [
      { id: "relationships", title: "إدارة العلاقات",  en: "Relationships",  mins: 11, kind: "theory" },
      { id: "datetable",     title: "جدول التقويم",    en: "Date Table",     mins: 14, kind: "code" },
      { id: "hierarchies",   title: "التصنيفات الهرمية", en: "Hierarchies",    mins: 7,  kind: "practice" },
    ],
  },
  {
    id: "dax",
    num: "04",
    title: "لغة التحليل DAX",
    en: "DAX — Data Analysis Expressions",
    subtitle: "Data Analysis Expressions",
    accent: "coral",
    lessons: [
      { id: "dax1",              title: "أساسيات DAX",                en: "DAX Basics",              mins: 10, kind: "code" },
      { id: "dax-logical",       title: "IF و SWITCH",                en: "Logical Functions",       mins: 13, kind: "code" },
      { id: "calculate",         title: "CALCULATE بعمق",             en: "CALCULATE Deep Dive",     mins: 20, kind: "code" },
      { id: "relationships-dax", title: "العلاقات داخل DAX",          en: "Relationships in DAX",    mins: 12, kind: "code" },
      { id: "iterators",         title: "دوال التكرار",                en: "Iterator Functions",      mins: 15, kind: "code" },
      { id: "dax2",              title: "ذكاء الوقت",                  en: "Time Intelligence",       mins: 18, kind: "code" },
      { id: "time-intel-pro",    title: "ذكاء الوقت المتقدم",          en: "Time Intelligence Pro",   mins: 22, kind: "code" },
      { id: "fieldparams",       title: "Field Parameters",            en: "Field Parameters",        mins: 11, kind: "practice" },
      { id: "dax3",              title: "DAX المتقدم",                 en: "Advanced DAX",            mins: 25, kind: "code" },
      { id: "dax-text",          title: "دوال النصوص",                 en: "Text Functions",          mins: 12, kind: "code" },
      { id: "dax-reference",     title: "مرجع DAX الكامل",             en: "DAX Reference",           mins: 9,  kind: "reference" },
    ],
  },
  {
    id: "visuals",
    num: "05",
    title: "التصميم البصري",
    en: "Visual Design & Visualization",
    subtitle: "Visualization & UX",
    accent: "violet",
    lessons: [
      { id: "visuals",         title: "المخططات البصرية",            en: "Visualizations",          mins: 14, kind: "practice" },
      { id: "sync-slicers",    title: "الـ Slicers والتفاعل",        en: "Sync Slicers",            mins: 9,  kind: "practice" },
      { id: "themes",          title: "الثيمات والتصميم",            en: "Themes & Design",         mins: 11, kind: "practice" },
      { id: "custom-tooltips", title: "Tooltips مخصصة",              en: "Custom Tooltips",         mins: 8,  kind: "practice" },
      { id: "condformat",      title: "التنسيق الشرطي",              en: "Conditional Formatting",  mins: 10, kind: "practice" },
      { id: "drillthrough",    title: "Drill Down و Drill Through",  en: "Drill Through",           mins: 11, kind: "practice" },
      { id: "bookmarks",       title: "الإشارات المرجعية",            en: "Bookmarks",               mins: 9,  kind: "practice" },
    ],
  },
  {
    id: "publish",
    num: "06",
    title: "النشر والإدارة",
    en: "Publishing & Governance",
    subtitle: "Publishing & Governance",
    accent: "gold",
    lessons: [
      { id: "publish",     title: "النشر والمشاركة",    en: "Publish & Share",        mins: 8,  kind: "practice" },
      { id: "workspaces",  title: "Workspaces و Apps",  en: "Workspaces & Apps",      mins: 10, kind: "practice" },
      { id: "rls",         title: "أمن الصفوف RLS",     en: "Row Level Security",     mins: 13, kind: "code" },
      { id: "gateway",     title: "Gateway والتحديث",    en: "Gateway & Refresh",      mins: 11, kind: "practice" },
      { id: "incremental", title: "Incremental Refresh", en: "Incremental Refresh",    mins: 14, kind: "practice" },
    ],
  },
  {
    id: "advanced",
    num: "07",
    title: "التميز والتحسين",
    en: "Advanced & Optimization",
    subtitle: "Advanced & Optimization",
    accent: "teal",
    lessons: [
      { id: "performance",         title: "الأداء والتحسين",       en: "Performance",            mins: 16, kind: "theory" },
      { id: "python-pbi",          title: "Python داخل Power BI",  en: "Python in PBI",          mins: 18, kind: "code" },
      { id: "paginated",           title: "التقارير الموجهة",       en: "Paginated Reports",      mins: 12, kind: "practice" },
      { id: "premium",             title: "مميزات Premium",         en: "Premium Features",       mins: 9,  kind: "reference" },
      { id: "external-tools",      title: "الأدوات الخارجية",        en: "External Tools",         mins: 11, kind: "reference" },
      { id: "apis",                title: "APIs و Embedded",        en: "APIs & Embedded",        mins: 14, kind: "code" },
      { id: "git-integration",     title: "Git و CI/CD",            en: "Git Integration",        mins: 10, kind: "reference" },
      { id: "advanced-dataflows",  title: "Dataflows المتقدمة",     en: "Advanced Dataflows",     mins: 13, kind: "practice" },
    ],
  },
  {
    id: "kpi",
    num: "08",
    title: "مؤشرات الأداء الرئيسية",
    en: "KPI Domains",
    subtitle: "KPI Domains",
    accent: "gold",
    lessons: [
      { id: "kpi-finance",   title: "المالية",         en: "Financial KPIs",   mins: 18, kind: "reference" },
      { id: "kpi-sales",     title: "المبيعات",        en: "Sales KPIs",       mins: 15, kind: "reference" },
      { id: "kpi-inventory", title: "المخزون والإمداد", en: "Inventory & Supply", mins: 16, kind: "reference" },
      { id: "kpi-hr",        title: "الموارد البشرية",   en: "HR KPIs",          mins: 14, kind: "reference" },
      { id: "kpi-marketing", title: "التسويق",         en: "Marketing KPIs",   mins: 13, kind: "reference" },
    ],
  },
];

// Flatten for progress tracking
window.ALL_LESSONS = window.CURRICULUM.flatMap(ch =>
  ch.lessons.map(l => ({ ...l, chapter: ch.id, chapterNum: ch.num, chapterTitle: ch.title, accent: ch.accent }))
);
